name: biosc1540-2024f-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - conda-lock
  - conda-forge::poetry
  - conda-forge::pre-commit
  - conda-forge::conda-poetry-liaison
  - nodejs
